python ray_train.py \
    -lr 1e-3 \
    -main-epoch 4000 \
    -num-tree-search 200 \
    -trainer-data-buffer-size 25 \
    -rollout-buffer-size 5 \
    -board-size 8\
    -num-in-a-row 5 \
    -batch-size 64 \
    -num-mini-epoch 1 \
    -eval-every 10 \
    -save-every 10 \
    -num-eval-matches 5 \
    -temp-decay-step 30 \
    -temp-decay-rate 0.1 \
    -update-threshold 0.65
